#apiVersion: v1
#kind: Service
#metadata:
#  name: django-app-service
#  labels: 
#    app: django-app
#spec:
#  type: NodePort
#  selector:
#    app: django-app
#  ports: 
#    - port: 8000
#      targetPort: 8000
#      nodePort: 31231

apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  labels: 
    app: django-app
spec:
  type: NodePort
  selector:
    app: django-app
  ports: 
    - port: 8000
      targetPort: 8000
      nodePort: 31231
