apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: django
  name: django-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /home/docker/food_project
    type: ""
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: django-pv-claim1
  volumeMode: Filesystem
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pv-claim1
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: django-pv # mount to this persistent volume  
---
